# Site settings
title: Jon D Moore
email: ReadReadRead19@gmail.com
description: 
baseurl: /
url: https://www.jondmoore.org
twitter_username: LutheranNerd
github_username:  JonDMoore

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
